### ISSUE TITLE
How to build this on linux ubuntuafter sudo ./install ?

### ISSUE THREAD

**Issue by WilliamWangPeng** [Victor-Haefner/polyvr#139]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)    

![image](https://user-images.githubusercontent.com/51076736/113842525-50824c00-97c5-11eb-9679-c795d6db986f.png)

thank you  
best regards to you  
William

**Comment by Victor-Haefner** [comment]
Hello William,

thank you for trying out PolyVR!
The install script is maybe a bit misnamed.. it actually just installs all the dependencies for compilation..
Did you load the Codeblocks project?
If you just installed Ubuntu it is probably 20.04, then you have to load PolyVR_20.04.cbp and compile and run it.

Remember to increase the compilation threads in codeblocks settings.
Check out the instructions in the README, at the bottom.

I also recommend to update [codeblocks](https://www.codeblocks.org/), there is also a PPA somewhere..

I do have cmake ready for windows and emscripten builds, but not yet for linux as I am used to codeblocks ;)
I may add it if people request it.

best regards,
Victor
