### ISSUE TITLE
physicalize tcmalloc

### ISSUE THREAD

**Issue by infobeisel** [Victor-Haefner/polyvr#27]
crash when trying to physicalize/ unphysicalize objects frequently or in mass.
errormessages:
- "../../thrid_pary/tcmalloc/chromium/src/tcmalloc.cc:286 attempt to free invalid pointer [pointeradress]"
- "../../thrid_pary/tcmalloc/chromium/src/free_list.h:118 Memory corruption detected."

**Comment by Victor-Haefner** [comment]
closing
