### ISSUE TITLE
Segemntation Fault bei Strokes und bestimmten Profilen und offenen Pfaden

### ISSUE THREAD

**Issue by Kai-W** [Victor-Haefner/polyvr#33]
#Profile
	VR.prof = []
	VR.prof.append([-bohrbreite,bohrhoehe,0])
	VR.prof.append([-bohrbreite,-bohrhoehe,0])
	VR.prof.append([bohrbreite,-bohrhoehe,0])
	VR.prof.append([bohrbreite,bohrhoehe,0])
	
	VR.prof2 = []
	VR.prof2.append([-bohrbreite,bohrhoehe,0])
	VR.prof2.append([-bohrbreite,0,0])
	VR.prof2.append([bohrbreite,0,0])
	VR.prof2.append([bohrbreite,bohrhoehe,0])

Profil 2 Fürht bei mir zu einem Segmentation Fault Wenn ich versuche einen Offenen Pfad von einer Box abzuziehen. Ein geschlossner Pfad führt zu keinem Absturtz. Bei bedarf kann ich das Testprojetk zusenden

**Comment by Victor-Haefner** [comment]
Please send me a test project file

**Comment by Victor-Haefner** [comment]
its ok, confirmed

**Comment by Victor-Haefner** [comment]
fixed, the crash was caused by flat triangles that CGAL did not like.
