### ISSUE TITLE
CEF javascript reload

### ISSUE THREAD

**Issue by fszeliga** [Victor-Haefner/polyvr#40]
When the project is closed and opened again (as means of resetting the project), changes in javascript are not reloaded (means that the old .js file is still in cache).

**Comment by prsbg** [comment]
Ich bin bis 24.08.2015 abwesend.

Vielen Dank f�r Ihre Nachricht!
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Thank you for your e-mail!
I will answer your message after my return.

Best regards,
Polina H�fner


*********************************



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[polyvr]
CEF javascript reload (#40)" gesendet am 08.08.2015 19:37:11.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.
