### ISSUE TITLE
Ubuntu 14.04 vrpn_* Headers on different location

### ISSUE THREAD

**Issue by destogl** [Victor-Haefner/polyvr#52]
Hello,

it seams that for some (for me unknown) reason vrpn_* header files are directly under `/usr/include` which make include from `vrpn/vrpn_*` impossible.

I am using lastes Ubuntu 14.04.

**Comment by Victor-Haefner** [comment]
Hi,

If you are using the package installed by the install script then the headers should be in
/usr/include/vrpn/

the package is also available here:
https://github.com/Victor-Haefner/polyvr-depends/tree/master/ubuntu_14.04

best regards,
Victor

**Comment by destogl** [comment]
I installed everything with `install` script. I am really not sure why this happened since few months ago everything worked fine...

if anyone else doesn't have the same issue in the next month I propose to just close it...

**Comment by Victor-Haefner** [comment]
This is really strange..
You could try:
`
cd polyvr/dependencies/ubuntu14_04/
sudo gdebi -n libvrpn-dev.deb
dpkg -s libvrpn-dev
`
does it install properly?
are there files in /usr/include/vrpn ?

**Comment by destogl** [comment]
Command `sudo gdebi -n libvrpn-dev.deb` gives me notification that later version of the library is alredy installed (Installed version is 07.30).

Comparing outputs of:
`dpkg-deb -c libvrpn-dev.deb` and
`dpkg-deb -c libvrpn-dev_07.30+dfsg-1~nd12.04+1+nd12.10+1+nd13.04+1+nd13.10+1+nd14.04+1_amd64.deb` (can be downloaded from [here](https://pkgs.org/ubuntu-14.04/neurodebian-main-amd64/libvrpn-dev_07.30+dfsg-1~nd12.04+1+nd12.10+1+nd13.04+1+nd13.10+1+nd14.04+1_amd64.deb.html))
it can be seen that repository package adds *.h file directly into `/usr/include/`

So this is error be probably older version of package than you provide... So I would say that issue is now solved :)

Thanks for help!

**Comment by Victor-Haefner** [comment]
yeah, I packaged it myself and changed the include path to not override other official packages of vrpn
