### ISSUE TITLE
Proposal for new blender ppa

### ISSUE THREAD

**Issue by Pfeil** [Victor-Haefner/polyvr#53]
The currently used blender ppa seems to be discontinued and is especially not available on Ubuntu 16.04. There is a new ppa which seems to continue the idea of the old ppa:

> A revival of Irie Shinsuke's Blender PPA: Blender is compiled with all bells and whistles (OSL, OpenCollada, OpenVDB, jemalloc), is GPU enabled and adapted to Ubuntu (Ubuntu packages such as ffmpeg, ilmbase, openEXR... are used), external libraries (OSL) are updated to recent versions. - https://launchpad.net/~thomas-schiex/+archive/ubuntu/blender

The PPA's `blender` package does the trick for me, currently on Ubuntu 16.04. I think this is currently the best choice for new Ubuntu releases.

**Comment by Victor-Haefner** [comment]
Seems fine, I will check the install scripts

**Comment by Victor-Haefner** [comment]
removed blender ppa alltogether, it caused issues when compiling on windows 10 ubuntu bash
