### ISSUE TITLE
Unable to import collada on Ubuntu 16.04

### ISSUE THREAD

**Issue by Pfeil** [Victor-Haefner/polyvr#54]
I installed PolyVR (latest, 3bd44a3a0cf403f36746bf240ef17e8e24f61a1e) on Ubuntu 16.04. Unfortunately, it seems that COLLADA (.dae) files are not loaded anymore. Here a small but complete PolyVR output of the `KA300.xml` example:

	Init PolyVR

	Parse command line options
	Init OSG
	FATAL: SharedObject::open: Could not open shared object 'libOSGImageFileIO.so':  libgdal.so.1: cannot open shared object file: No such file or directory
	ColorBuffer : 0x0000000000000001 
	DepthBuffer : 0x0000000000000002 
	GBuffer     : 0x0000000000000004 
	ShadowFactor: 0x0000000000000008 
	Init Modules
	Init VRSceneManager
	 PolyVR system directory: /home/verpfeilt/Code/polyvr
	 found glade file: ressources/gui/VRDirector.glade
	on_setup_changed
	Init VRViewManager
	Init VRWindowManager
	Init VRDeviceManager
	VRCamera::setup
	 load setup /home/verpfeilt/Code/polyvr/setup/Desktop.xml
	Load devices: keyboard mobile mouse
	 add Gtk window screen

	Init VRSceneLoader
	loadScene /home/verpfeilt/Code/polyvr/examples/KA300.xml
	Init VRCameraManager
	Init VRPhysicsManager
	VRDefShading
	Init Scene
	 init devices done
	 init scene done
	VRImport::load ../ressources/misc/Karlsruhe300.dae OSG
	RELOAD 0
	RELOAD 1
	load ../ressources/misc/Karlsruhe300.dae ext: .dae preset: OSG
	OSG Load ../ressources/misc/Karlsruhe300.dae
	WARNING: could not read /home/verpfeilt/Code/polyvr/examples/../ressources/misc/Karlsruhe300.dae; unknown file format
	VRImport::fillCache ../ressources/misc/Karlsruhe300.dae, cache size: 0
	VRImport::loadGeometry - Warning: ../ressources/misc/Karlsruhe300.dae in cache but has no object Plane0
	 cache root: ../ressources/misc/Karlsruhe300.dae cache size: 0
	failed to load Plane0 from file ../ressources/misc/Karlsruhe300.dae
	VRCamera::setup
	VRCamera::setup
	setIndices ld: 1
	setIndices ld=1
	WARNING: GeoSplitVertexArrayPumpGroup::masterAttribGeoPump: No positions.

The install script was executed without any errors. `libcollada-dev` is installed:

	> dpkg -s libcollada-dev
	Package: libcollada-dev
	Status: install ok installed
	Priority: optional
	Section: libdevel
	Installed-Size: 84600
	Maintainer: victor haefner <victor.haefner@gmail.com>
	Architecture: amd64
	Source: collada
	Version: 7.27-1
	Depends: libc6
	Description: COLLADA development package
	 COLLADA is great!
	Homepage: http://sourceforge.net/projects/collada-dom/

This also may be of interest to issue #9.

**Comment by Victor-Haefner** [comment]
There were issues with the collada dependency when compiling OpenSG a few months back for the 16.04 beta
I will recompile it soon

**Comment by Victor-Haefner** [comment]
done! update using:

cd polyvr/dependencies
sudo git pull
sudo gdebi -n libcollada-dev.deb
sudo gdebi -n libopensg-dev.deb

**Comment by Pfeil** [comment]
Works fine, thank you!
