### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by EdoFZI** [Victor-Haefner/polyvr#85]
Not able to build PolyVR.
Affected file: src/core/networking/VROPCUA.cpp
line: #include <opc/ua/node.h>

Error: fatal error: opc/ua/node.h: No such file or directory.

Folder is up to date with remote repository, correctly installed using <sudo ./install>.

**Comment by Victor-Haefner** [comment]
I guess the sub repo did not update correctly?
Check this with:
cd pathToPolyVR/dependencies
git pull

If this fails then try 
git pull origin master

which operating system are you working on?

**Comment by EdoFZI** [comment]
This solved the problem.
Thanks
